spring:
  application:
    name: student_log_api
  datasource:
    url: jdbc:postgresql://localhost:5432/Wallet
    username: postgres
    password: mojo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
server:
  port: 8080